# Generated by Django 3.0.3 on 2020-08-04 04:09

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='jop_type',
            new_name='job_type',
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to=job.models.image_upload),
        ),
    ]
